### ISSUE TITLE
Conferences detailed record

### ISSUE THREAD

**Issue by nikpap** [inspirehep/inspire-next#1001]
Issues to consider regarding the conferences detailed record:

- CNUM - do people understand/use this or is it mainly internal?

To be added:

- Contributions
- Other conferences in series

Mockup
![capture d ecran 2016-04-05 a 15 34 42](https://cloud.githubusercontent.com/assets/2742143/14283502/f6800620-fb43-11e5-8aa4-98e9d4dd2cff.png)

**Comment by bing13** [comment]
People actually seem to refer to the CNUM.

Nice use of maps. Really livens up what would otherwise be pretty sparse.

**Comment by annetteholtkamp** [comment]
Hi Nick,

the link to the proceedings and contribution records is still missing. But you're probably aware of that.
I'd take away the underscore in Alternative_titles.

Ciao - Annette


On 15 Mar 2016, at 11:29, Nick Papoutsis <notifications@github.com<mailto:notifications@github.com>> wrote:


Issues to consider regarding the conferences detailed record:

  *   CNUM - do people understand/use this or is it mainly internal?

To be added:

  *   Contributions
  *   Other conferences in series

WIP screenshot
[capture d ecran 2016-03-15 a 11 16 55]<https://cloud.githubusercontent.com/assets/2742143/13774473/8e28433a-ea9f-11e5-8cf8-0b7253ad34f4.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/inspirehep/inspire-next/issues/1001

**Comment by aw-bib** [comment]
For cnum I just introduced linkages from join2 systems to inspire using it, as it can be considered a persistent id. To get the cnum on board at our ends some visible display is helpful.

isRelatedTo: #981

**Comment by aw-bib** [comment]
BTW: I like the idea with the map. Ever thought about adopting OpenStreetmap instead of google? Just from one open project to the other. For Europe at least I found the OS maps usually quite a lot better then google. E.g. http://stackoverflow.com/questions/925164/openstreetmap-embedding-map-in-webpage-like-google-maps

**Comment by kaplun** [comment]
> Ever thought about adopting OpenStreetmap instead of google? Just from one open project to the other. For Europe at least I found the OS maps usually quite a lot better then google. E.g. http://stackoverflow.com/questions/925164/openstreetmap-embedding-map-in-webpage-like-google-maps

Although INSPIRE is an Open service to disseminate science in Open way we don't necessarily have to opt for Open solutions in aspects that are not core to the service.

Google Maps are way more used than OSM and would hence deliver a more integrated service to the majority of users  (e.g. imagine obtaining the directions to the select institute from your current position. It would integrate in a seamless way between your browser and your mobile etc.)

A side note from a development perspective: we have already experience with Google APIs and Google Maps specifically, which allows us to quickly deliver such functionality.
