### ISSUE TITLE
RFC Job ranks

### ISSUE THREAD

**Issue by tomaszgy** [inspirehep/inspire-next#1056]
-----

Problem
----------
In the two collections of INSPIRE (**Jobs** and **HepNames**) we store information about position's **rank**. For the Jobs it is job's rank, for HepNames - person's position in some institution during his/her career.

For both fields there have been performed some statistics over all the records we have in INSPIRE to see what are the most popular values. They can be found [here for HepNames](https://github.com/tomaszgy/inspire-next/blob/clean_mappings/inspirehep/dojson/current_marcxml_usage/hepnames.txt#L403) and [there for Jobs](https://github.com/tomaszgy/inspire-next/blob/clean_mappings/inspirehep/dojson/current_marcxml_usage/jobs.txt#L229). The charts below ilustrate the results:

#### Jobs

![amcharts 2](https://cloud.githubusercontent.com/assets/10139760/14637476/c2780456-0631-11e6-8e0d-a6dcb51be62e.png)
The value for rank has been found inside 413 records.

#### HepNames

![amcharts](https://cloud.githubusercontent.com/assets/10139760/14638210/98bd022e-0636-11e6-9ace-ee91f591082f.png)

The value for rank has been found inside 88787 records.

As can be seen, many of the values appear in both collections. Would it be possible to **standardize** the field **rank** so that it could contain values only from a given set of values (it would become an enum)?

### Proposal
It is proposed to establish the following set of values for the field:

- Staff
- Senior
- Junior
- Visiting Scientist
- PhD
- Postdoc
- Master
- Bachelor
- Undergraduate

#### Problems we might ought to cope with after doing so:

**1. How do we treat value _Student_ inside Jobs collection?**
We can allow the rank field inside Jobs to have multiple values so that it could contain: _Undergraduate_, _Bachelor_ and _Master_ at the same time instead of a simple _Student_.
Please correct me if I am wrong but it seems like this is what employer usually means when posting a job offer for a _Student_ (a person applying can be either  _Undergraduate_, _Bachelor_ or _Master_ )

**2. What do we do with other values that don't match any of the values proposed above?**
We can label them as _Other_ and append _Other_ to the proposed values.

### Why would we do it?

- we gain consistency of the data between collections
- it makes things cleaner for the users of INSPIRE
- it makes collections more searchable (e.g. we can apply filters on the ranks more easily)

### Questions:
1. Do you think it is a good idea?
2. Do you find a proposed list of values complete?
3. If not, what other values should be added?

CC: @inspirehep/inspire-dir, @jmartinm, @jalavik, @eamonnmag

**Comment by eamonnmag** [comment]
Hi @tomaszgy, this is great.

> Please correct me if I am wrong but it seems like this is what employer usually means when posting a job offer for a Student (a person applying can be either Undergraduate, Bachelor or Master )

Student means that the institution is advertising a PhD position. So it has a very specific meaning. 
You would not generally advertise for undergraduates or masters since those are taught programmes, but having them in the enum is ok.

Bachelors and undergraduate are almost synonyms in this context, so can be simplified to undergraduate.

So, now, you would have:
- Senior
- Junior
- Staff
- Visitor
- Postdoc
- PhD (Student)
- Masters
- Undergraduate

I believe that there should be more granularity on the positions. Senior and Junior are very vague in academic terms and could cover around 20 possible positions (see [here](https://en.wikipedia.org/wiki/Academic_ranks_in_the_United_Kingdom)).

**Comment by hoc3426** [comment]
I think this is a good list. "Senior" and "Junior" are purposefully vague
because it's practically impossible to get more specific without people
complaining that their position doesn't really fit into the category. We
originally had "Tenured" and "Tenure-track" and I'd get all these letters
saying "I'm not tenured" (though the person may have been in the position
for 20+ years). We also some confusion about "Staff" - this is meant to be
a non-research position, typically someone has when they leave HEP (e.g.
when I stopped being a postdoc and went to work in the SLAC Library running
SPIRES). However, we have a lot of lab scientists (as opposed to university
professors) choose this term because you hear "staff scientist" and "staff
position" at laboratories in general conversation. Maybe we need something
better?

**Comment by kaplun** [comment]
Mmh. Thinking of usescase: I now think we should be probably allow a very fine-grained set of intended positions, so that people can be clear about them if they wish, while still map them to a less granular way in order to be able to build statistics. What do you think?

We could then store the very fine-grained (but enumerated) list of authorized ranks, and also index them according to less-fine-grained mapping.

If Jobs are open to more ranks we can let users to specify a list of them.

**Comment by kaplun** [comment]
After discussion at stand up it was concluded to keep the short list, and to foreseen some mouse-over, or anyway detailed description of what it is meant with each category  ( @hoc3426 was volunteered to prepare the texts). So:
```
Senior
Junior
Staff
Visitor
Postdoc
PhD
Masters
Undergraduate
```

**Comment by tomaszgy** [comment]
Great, thank you @kaplun, @eamonnmag and @hoc3426 for contribution.

**Comment by eamonnmag** [comment]
@kaplun perhaps, having this list as the keys in some dict structure which could host some more specific job titles would be nice.

```
{
    'senior': ['Professor', 'Emeritus Professor', ...],
    'junior': ['Junior Professor', 'Associate Professor', ...],
    'staff': ['Research Scientist', 'Research Associate', ...],
    ...
}
```

But this is a further detail. I think it's best to move on to start getting the content in shape using this taxonomy, then more refinement can appear later.
