### ISSUE TITLE
INSPIRE or Inspire or inSPIRE or ...?

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1101]
This question keep on coming on and on. What is the nowadays (or desired future) name of INSPIRE? This is important especially when outreaching (talks, presentation, papers)...

* [ ] INSPIRE
* [ ] Inspire
* [ ] inSPIRE
* [ ] Other proposal?

cc: @inspirehep/inspire-dir

**Comment by bing13** [comment]
For the most part I think we've used INSPIRE pretty consistently. I think it works pretty well for our branding purposes.  
It's a common english word, and yet if you google "inspire", we come up as the fourth hit (at least in my search bubble).  Not bad.

**Comment by kaplun** [comment]
First result in my bubble :-) but so you would propose to keep it all upper case?

**Comment by bing13** [comment]
Yes. 
There is nothing distinctive about the word by itself. Rendering it in all caps makes it more recognizable as a brand.

**Comment by hoc3426** [comment]
I completely agree with Bernard, it's INSPIRE, and we refer to it as such
pretty consistently throughout the site. One could argue, perhaps, that the
logo makes this a little ambiguous however...

**Comment by aw-bib** [comment]
- There is [INSPIRE](http://inspire.ec.europa.eu/) (all caps)
- Our current logo seems to read a lower case _i_ or lower case  _in_ (if the font is considered sc)
- The dot in the logo seems to intend _i_ instead of _I_
- Labs writes it entirely lower case again with a prominent dot on the i to add some colour / display the collection (I guess the chemical symbol and _labs_ repeating the colour will go away on prod?)
- logo and name should get in sync

**Comment by jmartinm** [comment]
INSPIRE seems to be the conclusion?

We can close that in that case and we will make sure in future development that we are consistent (including Labs logo)

**Comment by kaplun** [comment]
Yes. `INSPIRE` shall be!
