### ISSUE TITLE
RFC: Use UUIDs as canonical ids

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1139]
Follow up of https://github.com/inspirehep/inspire-next/issues/1038

Proposal to move from `recids` to `uuids` as a canonical identifier for records.

Pros
====

* Consistency between ElasticSearch ids and record ids. For example if we write corresponding recids close to each reference, then we cannot get from ElasticSearch all references at once with one `mget` call. See https://github.com/inspirehep/inspire-next/issues/1038#issuecomment-220973004

* Avoid one level of indirection when retrieving records. At the moment, if the starting point is a `recid`, we always have to first query the DB (see [example](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/utils/record_getter.py#L68)), and then either do another query in the DB to fetch the record or do a query to ES. Starting from UUID we could directly get the record from DB or ES with one query.

Cons
====

* Longer (not easy to remember) URLs, such as `http://inspirehep.net/literature/5b6b3a6d-b590-43a7-a10e-309b040e5c22` VS `http://inspirehep.net/literature/123456`

* Change URL format from current http://inspirehep.net

**Comment by jmartinm** [comment]
I am sure the list is not complete, please comment here for more pros and cons of this change and I will update the main description.

**Comment by jalavik** [comment]
I note that legacy recids will still resolve in this schema (but then via the PIDstore resolver). I guess, in the Records REST API we'd have to have a special case in our PID resolver where UUIDs are not resolved via PIDStore but returned directly? (basically skipping PIDStore unless looking up with legacy recid). Guess we'd have a `is_uuid` check in the resolver.

**Comment by jmartinm** [comment]
One question would be for new records, do we still mint a recid for them or they only have UUID?

**Comment by kaplun** [comment]
@jalavik at the forum, Jiri was recommending not to expose UUID, but always to use some other PID. At worst, to explicitly register the UUID as an additional PID.

**Comment by kaplun** [comment]
Plus what about author profiles? Shall we still maintain `B.Storaci.1`?

IMHO we can keep with the current behaviour of recids. Lars was mentioning in another discussion that using plain integer (as much as UUID actually) is not actually recommended, because it doesn't give you any hint at the namespace.

In principle we could invent new identifiers such as INSPIRE-LIT-123 etc. In this way from the identifier it is clear the service, the document type and it's unique.

**Comment by eamonnmag** [comment]
I'm just seeing this conversation now, so apologies for not coming in sooner. 

The namespace is in the URL - https://qa.inspirehep.net/authors/984446. Having an additional identifier won't be incredibly useful. B.Storaci.1 should be an alias, not the official identifier. These should always be numbers. 

To be honest, the UUID is completely useless and just increases db size and reduces performance (see [here](http://kccoder.com/mysql/uuid-vs-int-insert-performance/)) with no benefit in inspire or hepdata for instance where there is only a single DB. A simple count on the id on the records table would have been sufficient. But I've said this before but no notice was taken. So hide the UUIDs as much as possible, they should never be exposed to the user.

**Comment by kaplun** [comment]
@eamonnmag see also #981 

About the speed, anyway UUID is buried in invenio-records+invenio-pidstore+ES, so unless we don't use these modules or we modify them, we are still impacted by the performance issue.

WRT namespace indeed it's in the URL, but then are we saying the full URL has to be used as identifier? I.e. when someone wants to referer to a given object in INSPIRE, has to use the full URL? 

Imagine DOIs, ISBNs, strings etc. They all convey (more or less) just by their intrinsic format they all convey what they are, and with that what to do with them.

With just plain integers, one doesn't have enough context to know what to do.
See e.g. Lars on the topic  https://github.com/inspirehep/inspire-next/issues/981#issuecomment-194782464

**Comment by lnielsen** [comment]
Some info you can to take into consideration if you like:

- **UUIDs are just 128-bit numbers** - you could represent them as integers, but it probably wouldn't make them any prettier :D Storage-wise it's just double the size of a bigint.
- **UUID use in Invenio**:  We use UUIDs extensively in Invenio as primary keys because they can easily be generated from any piece of code without any knowledge of global state (compared to an incrementing sequence of integers which require transaction management in order to avoid minting the same id twice - i.e. knowledge of global state). Also UUIDs are very likely to be unique if you later needed to merge separate systems.

*Persistent identifiers* comes in two types:
- Using native URLs via http/https scheme
- Using a resolver authority (i.e. DOIs, purls, handle, isbn, orcid, ...)

IMHO integers + UUIDs (with a resolver) are not useful as persistent identifiers as their identifier scheme is not easily detectable (i.e. given a UUID/int, you can't tell that it's an Inspire ID).

URLs are definitely useful as persistent identifier, but 1) you must expose the URL as *the* identifier (not just some half version of it) and 2) since there's no resolver, it can be quite hard to actually keep them persistent (e.g. hostname changes, repo software is upgrade etc).

For more info have a look at https://doi.org/10.7717/peerj-cs.1

**Comment by salmele** [comment]
While I see the point of enormously long IDs in URLs, I do not think that our system, one in which people would like to refer to things sending e-mails and sometimes (horror!) using URLs in reference lists of their papers as is, would stand to gain by exposing them.

Which leaves open the point:

> In principle we could invent new identifiers such as INSPIRE-LIT-123 etc. In this way from the identifier it is clear the service, the document type and it's unique.

There, I am a bit concerned by too many changes at once when moving into a new system, and the possibility that users might start using things like INSPIRE-LIT-123  in lieu of DOIs when writing reference lists. It can introduce, by its officially looking shape, an undesired behavior. We do know that users struggle to see how to quote some material we host and for which there is no publication note, DOI or even preprint number. That's where that behavior would come from. So far, that's why indeed they use URLs

> I.e. when someone wants to referer to a given object in INSPIRE, has to use the full URL?

This is what users have been doing to date, and it might be not so bad, with the exception of authors profiles which sometimes are even built as canned search. 

> Plus what about author profiles? Shall we still maintain B.Storaci.1?

As this is what users use, yes, I think we shall maintain it. Come to that, it could even become a vanity URL http://inspirehep.net/B.Storaci.1. Maybe we could think about how this conceptually can be used in lieu of a number in the way users see URL

In any case, with the (to be deprecated)  INSPIRE-ID for authors, the B.Storaci.1 and later the ORCID iDs, it would not be wise to introduce something else for authors.

**Comment by jmartinm** [comment]
Closing this as we seem to agree that the course of action at the moment is to continue exposing integers (recids) for linking and URLs.
