### ISSUE TITLE
records are under authorization

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1285]
Records are currently not accessible without authorization.

I assume this might be happening after https://github.com/inspirehep/inspire-next/commit/668309951dfca65cab3bbf09e76f804203ef7188 was introduced.

By adding some permissions to a user, it might be that guests now cannot access records as `invenio-access` allows everybody to do all actions until the action is assigned to some user.

This needs to be checked.

**Comment by jacquerie** [comment]
There are two bugs here.
1. The first is an unexpected default in Invenio-Access, as I try to explain here: https://github.com/inveniosoftware/invenio-access/issues/71
2. The second is the fact that our test suite is not catching this, and this is because the `app` fixture doesn't run the `fixtures` command that adds the superuser.
