### ISSUE TITLE
8564_w not present in data model

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1430]
The data model in inspirehep.net for URLs looks like:

![screen shot 2016-08-11 at 9 22 26 am](https://cloud.githubusercontent.com/assets/580727/17581294/25efb804-5fa5-11e6-9445-52350feeb3eb.png)

And the new data model has `value` and `description`:

``` json
"properties": {
        "description": {
            "type": "string"
        },
        "value": {
            "format": "url",
            "type": "string"
        }
    }
```

While implementing the journals detailed view I have seen that we are missing some information that is contained in `8564_w`  and used to describe what volume the URL corresponds to:

https://inspirehep.net/record/1214516

Would it be enough to use the description field for this? Or we think we need a new field?

**Comment by kaplun** [comment]
@inspirehep/inspire-content what is the meaning of `8564 $w` indeed? Many records have it but is not used in formats and I doubt it is searched. How is it populated?

**Comment by kaplun** [comment]
For reference this is connected with #463

**Comment by ksachs** [comment]
this goes back to SPIRES where we had 2 pieces for a URL: 
the base-part as a lookup-table/knowledgebase ($$y)+ the specific piece for this paper ($$w)
This made it easier to move the URLs in case the server changed.

e.g.
$$y:JACOW -> http://accelconf.web.cern.ch/AccelConf/
+
$$w:p91/PDF/PAC1991_1461.PDF
=
http://accelconf.web.cern.ch/AccelConf/p91/PDF/PAC1991_1461.PDF

30751 8564_ $$uhttp://accelconf.web.cern.ch/AccelConf/p91/PDF/PAC1991_1461.PDF$$wp91/PDF/PAC1991_1461.PDF$$yJACOW

**Comment by kaplun** [comment]
Oooh. Interesting. Isn't this then superseded nowadays by careful usage of 035, where we just store the external ID, and we are then able to link to the splash page of the document?  Because in principle also the $w value in your example could be subject to changes by the external service.

I see also that the URL in $y is anyway the full one, so $w contains just the suffix. So in principle we can ignore it during the migration, and in case move those URLs to use the 035 technique.

**Comment by hoc3426** [comment]
Yes, 035 and 0247 (DOI) have largely done away with any need for this.

**Comment by annetteholtkamp** [comment]
Anyway, all these have been expanded into a complete url when migrating from Spires to Inspire. This subfield has never been used in Inspire as far as I’m aware.

- Annette

**Comment by kaplun** [comment]
@inspirehep/inspire-content I realize now that this specific issue @jmartinm raised was related to journal database. What shall we do with 8564_$w in that case?

**Comment by hoc3426** [comment]
These can be handy, if, say, you want to show everything that is linked to
"symmetry" magazine, but we probably contain the necessary information in
the $y field now.

**Comment by annetteholtkamp** [comment]
There are only 9 journal records affected. Either it says Open Access - this info should definitely go somewhere else.
http://journals.aps.org/prab/ <http://journals.aps.org/prab/> (Open Access)
Or it specifies in case of subseries A,B… to which subseries a url belongs. 
.	
Physical Review  <https://inspirehep.net/record/1214516>
Phys.Rev. 
http://pra.aps.org <http://pra.aps.org/> (A)
http://prb.aps.org <http://prb.aps.org/> (B)
http://prc.aps.org <http://prc.aps.org/> (C)
http://prd.aps.org <http://prd.aps.org/> (D)
http://pre.aps.org <http://pre.aps.org/> (E)

Since we intend to create separate records for the subseries these url’s just have to be added to the right records. Then this subfield becomes obsolete.

- Annette

**Comment by jacquerie** [comment]
This issue was moved to inspirehep/inspire-schemas#211
