### ISSUE TITLE
RFC enhancing records

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1448]
Currently, on legacy, a record A refer to a record B by either the record ID of B being present somewhere in the metadata of A, or by one of the identifiers of B being written somewhere in the metadata of A (e.g. a proceeding can refer to a conference through the CNUM).

When exporting records from legacy an enhanced format is used, that automatically resolves identifiers and add the corresponding record IDs.

https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py

To dump the whole legacy data is a very heavy task (due to the many suboptimal SQL queries involved).

In principle, beside adding BAIs and FFTs (which is done by the enhanced format and can't be done by simply querying records), the other enhancements could be done on Labs, as a before_record_insert/update activity.

In practice every place in our schemas where we have a `$ref` will have a dedicated enhancer that is able to look at some identifier next to it and correspondingly populate the `$ref`.

@jacquerie @jmartinm @eamonnmag @david-caro WDYT?

Is this issue enough clear?

**Comment by liamkirsh** [comment]
This is an issue for the HAL TEI module because the HAL SWORD API requires each author to have an associated affiliation, linked through an ID (HAL or non-HAL). A workaround in the meantime is to just use random IDs or count starting at 1, being sure to avoid any conflicts.

Submitting a record with an author but no affiliation info causes the following error:

`<?xml version="1.0" encoding="utf-8"?>
<sword:error xmlns:sword="http://purl.org/net/sword/error/" xmlns="http://www.w3.org/2005/Atom" href="http://purl.org/net/sword/error/ErrorBadRequest">
  <title>ERROR</title>
  <updated>2016-08-17T19:17:06+02:00</updated>
  <author>
    <name>HAL SWORD API Server</name>
  </author>
  <source>
    <generator uri="https://api-preprod.archives-ouvertes.fr/sword" version="1.0">hal@ccsd.cnrs.fr</generator>
  </source>
  <summary>Some parameters sent with the request were not understood</summary>
  <sword:treatment>processing failed</sword:treatment>
  <sword:verboseDescription>{"author":["Missing affiliation for at least one author"]}</sword:verboseDescription>
  <link rel="alternate" href="https://api-preprod.archives-ouvertes.fr" type="text/html"/>
</sword:error>`

**Comment by kaplun** [comment]
@liamkirsh thanks for pointing that out. Alternatively you can simply put a dummy value, but we should definitively contact them and let them know this is too strict.

**Comment by jacquerie** [comment]
> Is this issue enough clear?

Err... not for me.

Here's my understanding. In "Legacy" some values are actually used as foreign keys to other "tables": for example, experiment names in a HepNames record are foreign keys to experiments in Experiments. When enhancing a query is run that resolves this foreign key to an actual record, and a recid is added to the metadata.

"Next" starts from this enhanced record, therefore it already has these recids in the metadata, hence it doesn't need enhancers. Or am I missing something?

**Comment by kaplun** [comment]
It wouldn't need enhancers in the migration context but:
* resolving these in legacy is deadly slow
* what about when Labs is running on its legs? If a cataloguer touches the name of the experiment in HEP, will the reference be automatically updated? How? By record-editor or by a `before_record_update` task?

**Comment by jacquerie** [comment]
Ok. Using names as foreign keys was and would be a bad idea in the future, so let's not do that (name collisions happen). IMO this should happen in `record-editor`: in order to present the choice to the cataloguer `record-editor` has to load a list of `recid`s and names; if the cataloguer selects a name then we already have the recid there, so there's no need for an enhancer to run afterwards. If the cataloguer wants a new name then there's probably no record for it, so a `recid` has to be created anyway.

Also, we should be thinking in terms of "reference changes -> name changes" rather than "name changes -> reference changes".
