### ISSUE TITLE
HAL Domains

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1590]
HAL Domains are here:
https://api-preprod.archives-ouvertes.fr/ref/domain/?fl=code_s,label_s&rows=500

We need a mapping between arXiv categories and INSPIRE categories to HAL categories.

**Comment by kaplun** [comment]
@annetteholtkamp can you help us with this?

**Comment by annetteholtkamp** [comment]
We just have 14 subjects. I would map them in the following way:

  Astrophysics						edu.astr
   Accelerators						phys.phys.phys-acc-ph
   Computing						info
   Experiment-HEP					phys.hexp
   Gravitation and Cosmology			phys.grqc
   Instrumentation					phys.phys.phys-ins-det
   Lattice							phys.hlat
   Math and Math Physics			math
   Theory-Nucl						phys.nucl
   Other
   Phenomenology-HEP				phys.hphe
   General Physics					 phys.phys.phys-gen-ph
   Theory-HEP						phys.hthe
   Experiment-Nucl					pays.nucl

I don’t know what to do about “other". For Mathieu to say.

- Annette

**Comment by mathieugrives** [comment]
I think this link gives a more human readable look at HAL domains : https://hal.archives-ouvertes.fr/browse/domain
It seems to stick at arXiv categories and the specific HAL term is visible in the weblink of each.
Watch carefully because, for example, I can see that there are astrophysics under physics called phys.astr but the sames under "planètes et univers" are called sdu.astr...

For "other", I'll ask because I'm not that familiar with HAL. For example, there is one for astro called sdu.other, but not for physics or general. I'll tell you tomorrow.

**Comment by mathieugrives** [comment]
As there is no "phys.other", Sandrine and I suggest to put the Inspire "other" into "phys".

Hal domains are quite a messy and not so important tool, so I advise you to stay general and do not bother too much with this.

**Comment by jacquerie** [comment]
In the end I'm using the following mapping:

```python
HAL_DOMAIN_MAPPING = {
    'Accelerators': 'phys.phys.phys-acc-ph',
    'Astrophysics': 'phys.astr',
    'Computing': 'info',
    'Data Analysis and Statistics': 'phys.phys.phys-data-an',
    'Experiment-HEP': 'phys.hexp',
    'Experiment-Nucl': 'phys.nexp',
    'General Physics': 'phys.phys.phys-gen-ph',
    'Gravitation and Cosmology': 'phys.grqc',
    'Instrumentation': 'phys.phys.phys-ins-det',
    'Lattice': 'phys.hlat',
    'Math and Math Physics': 'math',
    'Other': 'phys',
    'Phenomenology': 'phys.hphe',
    'Theory-HEP': 'phys.hthe',
    'Theory-Nucl': 'phys.nucl',
}
```
