### ISSUE TITLE
RFC Make $refs flatter

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1662]
At the moment, all our `$ref` between records use [this element](https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/elements/json_reference.json) and we are always nesting $ref inside of some other object, for example:

```
"record": {
    "$ref": "elements/json_reference.json",
    "description": "URI for the corresponding experiment record."
}

```

which means that final records look like:

```
 {
                     "record": {
                        "$ref": "http://localhost:5000/api/literature/462477"
                     },
```

This makes users of our documents (like the record editor) have to access a complex object, looking for example like:

<img width="672" alt="screen shot 2016-10-19 at 5 16 55 pm" src="https://cloud.githubusercontent.com/assets/580727/19527415/3c5eacd0-9628-11e6-97a7-4f5564cc4295.png">

Is there a reason for this? Would it possible to have flatter structure?

The latest version of the JSON-reference spec https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3 says:

> A JSON Reference is a JSON object, which contains a member named
>    "$ref", which has a JSON string value.  Example:
>    { "$ref": "http://example.com/example.json#/foo/bar" }

so $ref does not need to be on its own.

@jacquerie @kaplun thoughts?

**Comment by kaplun** [comment]
As discussed in chat this originate from JSON ref usage in JSON Schema which requires $ref to be nested in order to allow substitution of the reference with the referred object.

That said: in real life I can't think of a situation where we are going to substitute a reference with the referred record. We might want to borrow some properties of referred records into the referring one for indexing purposes, but since this has to be done ad-hoc anyway, IMHO we don't need to stick to jsonschema convention.

My only worry here is if we don't see coming some further issue in some invenio component that follows this convention.  I doubt it though.

Anyone else?

CC: @spirosdelviniotis who is amending all mappings to index $ref in #1660.

**Comment by kaplun** [comment]
One issue I just found: https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/hep.json#L611-L655

If we don't nest `$ref` into a `*record` property, how do we distinguish among multiple links to other records at the same level? E.g.:
https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/hep.json#L611-L655

Here we have potentially a link to a journal record, to a conference record and to a parent record. How can we make this obvious that these are links without nesting `$ref`?

Shall we have a convention?

`$journal_ref`, `$conference_ref`, `$parent_ref` with the implied convention that `$` means reference...

**Comment by kaplun** [comment]
Actually according to https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03 the usage we have done so far is respecting the JSON-Ref standard.

I wonder: if the issue is only related to JSON Editor, and since we were saying in the past that Catalogers should not really have to enter the URL by hand, rather choosing from drop-down/autocomplete, maybe a bettter visualization is possible?

**Comment by jmartinm** [comment]
> I wonder: if the issue is only related to JSON Editor, and since we were saying in the past that Catalogers should not really have to enter the URL by hand, rather choosing from drop-down/autocomplete, maybe a better visualization is possible?

If we always keep the same convention that $ref is alone in an object I am sure we can do something to detect it and we will create a component that shows a search bar to find the linked record. @harunurhan any thoughts on what would make the development of the record editor easier?

**Comment by kaplun** [comment]
Actually we were just musing with @michamos in this very instant: if the cataloger needs to add a reference to a record that does not yet exist (say a new journal or a new conference), in an ideal implementation she should be able to pop-up a record editor/form to edit the new conference/journal, that then can be used for autocomplete.

How to best implement this is an open question to me.

@david-caro points out also, that we would need to know the type of allowed records that we can autocomplete from/link to, but that I guess is solvable by json-editor configuration.

**Comment by jmartinm** [comment]
This is not needed for the moment. As long as we keep the same structure for $refs we know deal with them appropriately in the editor.

**Comment by annetteholtkamp** [comment]
and/or create a dedicated ticket to refer this task to a specialised curator, e.g. Melissa for journals.

- Annette


On Oct 20, 2016, at 11:08 AM, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually we were just musing with @michamos<https://github.com/michamos> in this very instant: if the cataloger needs to add a reference to a record that does not yet exist (say a new journal or a new conference), in an ideal implementation she should be able to pop-up a record editor/form to edit the new conference/journal, that then can be used for autocomplete.

How to best implement this is an open question to me.

@david-caro<https://github.com/david-caro> points out also, that we would need to know the type of allowed records that we can autocomplete from/link to, but that I guess is solvable by json-editor configuration.
