### ISSUE TITLE
litterature suggest form: there's an error shows just after hitting submit and redirecting to the 'submission done' page

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1947]
We should not show it if possible.

**Comment by jmartinm** [comment]
I think I have seen this some time but locally cannot reproduce it. Do you have the steps to reproduce?

**Comment by rikirenz** [comment]
The issue can be reproduced with Firefox

**Comment by rikirenz** [comment]
I checked this issue with Firefox. During the debug phase I was not able to reproduce the error. I put a breakpoint in the line that was supposed to trigger the error but that specific line is never triggered when the developer console is open. Indeed I have never seen the error during the debug. 
I checked also with @harunurhan in order to see if I was missing something during the debug procedure.

The only thing that I tried and it is able to **Hide** the problem, was remove this specific line:

https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/forms/static/js/forms/inspire-form.js#L500

@jmartinm I am sorry if you have time please check it. Even though I do not think is a big issue.

**Comment by jmartinm** [comment]
@rikirenz can you try this? https://github.com/inspirehep/inspire-next/pull/2014
