### ISSUE TITLE
holding pen litterature detail: when inserting a subject, the autocomplete list does not highlight the selected option

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1951]
![screenshot from 2017-03-02 15-51-48](https://cloud.githubusercontent.com/assets/587148/23512288/67c2e6ce-ff60-11e6-96f7-ebb8fddfc10a.png)

**Comment by jmartinm** [comment]
I was going to remove the possibility of adding categories there actually. Otherwise we need to maintain code in the Holding Pen to only allow certain subjects and it gets a bit complicated now with authors and hep having different `categories`. Since we will have the editor one can add subjects there.
