### ISSUE TITLE
holding pen: results per page

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2010]
'Number of records found' close to 'results per page', so it's easier to adjust the number.
Can we get 'all' in the pull-down 'Results' by page?
(request by Kirsten)

**Comment by jmartinm** [comment]
> 'Number of records found' close to 'results per page', so it's easier to adjust the number.

@StellaCh what do you think? Might be good to move the `Results per page` and `Sort by` to the top of the results like we have in search pages:

<img width="901" alt="screen shot 2017-03-10 at 1 26 47 pm" src="https://cloud.githubusercontent.com/assets/580727/23796943/7777ed4a-0595-11e7-9fa0-960192460176.png">

And leave on the left only the facet filters.

> Can we get 'all' in the pull-down 'Results' by page?

That would not be possible since we are going to have potentially thousands of holding pen entries in the future with harvests, user submissions and so on. Showing them all would kill the browser.

**Comment by StellaCh** [comment]
I agree, it sounds reasonable. What's the maximum amount of results per page that we can have with this solution?

**Comment by jmartinm** [comment]
> I agree, it sounds reasonable. What's the maximum amount of results per page that we can have with this solution?

We need to test it.

Now that I think about it another solution is to have lazy loading. That means that as you scroll down more results are being loaded so it basically simulates like if you had all of them.

**Comment by jacquerie** [comment]
> Now that I think about it another solution is to have lazy loading. That means that as you scroll down more results are being loaded so it basically simulates like if you had all of them.

This reminds me: we are not using anywhere the [`Scroll API`](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-scroll.html) to paginate results, which means that http://inspire-nightly.cern.ch/search?page=399&size=25&cc=literature&q= works, while http://inspire-nightly.cern.ch/search?page=400&size=25&cc=literature&q= raises an exception (it hits the 10k limit).

**Comment by StellaCh** [comment]
Closing this ticket as the impact is really small
