### ISSUE TITLE
dojson: keywords from magpie should not be sent to legacy

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2146]
keywords guessed by magpie end up in `653` instead of `695`: https://inspirehep.net/search?ln=en&p=653%3Amagpie&of=hb&action_search=Search&sf=earliestdate&so=d.

EDIT by @kaplun: we should not send them back to legacy.

**Comment by kaplun** [comment]
This is a feature rather than a bug.
It has been pointed out today at standup that magpie keywords are actually serving a different purpose than bibclassify keywords (discoverability of similar topics, Vs. exact search).

Since we should not change the behavior on legacy it's better not to send magpie keywords back to legacy at all..

**Comment by michamos** [comment]
fixed by #2217
