### ISSUE TITLE
Records harvested on legacy are still harvested on Labs

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2310]
https://labs.inspirehep.net/holdingpen/629463 this has astro.CO and should have not been harvested.

cc @ksachs

**Comment by jacquerie** [comment]
What?

That is a math.CO paper. We're going to harvest those papers, because they are not in https://github.com/inspirehep/inspire-next/blob/9a3770ba2f64571e7d336eafddaed50ecce88cfe/inspirehep/config.py#L1374-L1386, the categories harvested on Legacy. It will then be rejected, because the conditions in #2115 will not be satisfied.

So I think that this is just a repetition of #2309, which notes that #2115 was incorrectly implemented in #2142.

**Comment by ksachs** [comment]
Sam means https://labs.inspirehep.net/holdingpen/629448 which is astro-ph.CO

**Comment by jacquerie** [comment]
Oh. Then I see why: the configuration has `astro-ph.co`, the record has `astro-ph.CO` (note the different capitalization), so they have empty intersection and this records comes through. It's an easy fix.

**Comment by jacquerie** [comment]
I just deployed this fix.

**Comment by kaplun** [comment]
> Sam means https://labs.inspirehep.net/holdingpen/629448 which is astro-ph.CO

Yeah! Sorry for the wrong cut & paste!

> Oh. Then I see why: the configuration has astro-ph.co, the record has astro-ph.CO (note the different capitalization), so the record comes through. It's an easy fix.

Damn! Thanks for the fix. I hope we have normalized these categories for the good!
