### ISSUE TITLE
Move dojson to its own package

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2356]
In order to be able to use dojson easily from hepcrawl to ingest marcxml records, it would be really helpful to have dojson on it's own package so we can reuse the same code to transform the record to json.

**Comment by david-caro** [comment]
@jacquerie @kaplun @jmartinm what do you think? It's mainly to be able to have the desy spider, that directly ingests marcxml records, so we can avoid having to reimplement the 50+ spiders they currently have before we make labs the master.

**Comment by david-caro** [comment]
Being fair, it's 47, but well... does not make much of a difference here.

**Comment by jacquerie** [comment]
BTW the separation would a nice time to solve https://github.com/inspirehep/inspire-next/issues/2248.

**Comment by david-caro** [comment]
:+1:


--
David Caro <david.caro@cern.ch>

CERN - RCS-SIS
inSPIRE-HEP High Energy Physics information system
http://inspirehep.net
On May 18, 2017 22:45, Jacopo Notarstefano <notifications@github.com> wrote:

BTW the separation would a nice time to solve #2248<https://github.com/inspirehep/inspire-next/issues/2248>.

**Comment by kaplun** [comment]
Yeah: inspire-dojson and we can be happy. Only issue (as for the inspire-jsonmerger) is that, since `inspire-dojson` will depend tightly on `inspire-schemas` we will have to be careful to always update `inspire-schemas` and `inspire-dojson` at the same time in `inspire-next`. I.e. we might slightly complicate the dependency cicles, but at least it's for a very good cause of saving energy.

**Comment by jacquerie** [comment]
Now it would be a good time to do it: after https://github.com/inspirehep/inspire-next/pull/2470 we have parity between `inspire-schemas` and `inspire-next`.
