### ISSUE TITLE
Upgrade issue with collection tag

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#251]
We have an issue with the upgrade script `collections_2015_05_28_recjson_tag_value`

I think the reason is simply that the tag is named differently on INSPIRE:

```sql
SELECT id,name,value FROM tag where value like '%980%';
+----+--------------------+--------+
| id | name               | value  |
+----+--------------------+--------+
| 51 | collection         | 980__a |
| 52 | collection deleted | 980__c |
+----+--------------------+--------+
2 rows in set (0.00 sec)
```

While the upgrade script checks for `name == "collection identifier"`.

Is it safe to simply rename on INSPIRE to `collection identifier`?

@kaplun @jmartinm 

EDIT: I noticed this when running `inveniomanage upgrader check`:

```
>>> Running pre-upgrade checks...
>>> ERROR: Pre-upgrade check for collections_2015_05_28_recjson_tag_value failed with the following errors:
 (-) Missing 'collection identifier' tag.
>>> ERROR: Upgrade check failed. Aborting.
```

**Comment by jmartinm** [comment]
That upgrade recipe seems to be related to the Invenio demo site https://github.com/inveniosoftware/invenio-demosite/blob/master/invenio_demosite/base/recordext/fields/atlantis.cfg#L196

On INSPIRE we actually don't have such a thing in ``inspire.cfg``.

To be safe I think we should update all our dbquery (https://github.com/inspirehep/inspire-next/blob/master/inspire/base/mixer/sources/collection.json) from ``980__a: -> collection:`` so that it is clear that the collection tag needs to be used (and so that it works properly [here](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/collections/recordext/functions/get_record_collections.py#L27))

Then we need to do in labs:

```SQL
UPDATE tag SET value="", recjson_value="_collections" WHERE name="collection"; 
```

**Comment by jmartinm** [comment]
Seems like the assumption was not correct. After changing the dbqueries to the format ```collection:HEP``` and reindexing the ```collection``` index the records cannot be found (so they are not correctly indexed in the collection).

After debugging a bit more to make sure:

```sql
|  4 | Conferences            | collection:CONFERENCES
```

```python
In [1]: from invenio.modules.records.api import get_record

In [2]: x = get_record(12)

In [3]: from invenio.modules.collections.recordext.functions.get_record_collections import get_record_collections

In [4]: get_record_collections(x)
Out[4]: []
```

Changing to:

```sql
|  4 | Conferences            | 980__a:"CONFERENCES"
```

```python
In [1]: from invenio.modules.records.api import get_record

In [2]: x = get_record(12)

In [3]: from invenio.modules.collections.recordext.functions.get_record_collections import get_record_collections

In [4]: get_record_collections(x)
Out[4]: [u'Conferences']
```

So based on our current data model, seems like it is best to leave the dbqueries with 980.

**Comment by jmartinm** [comment]
For the initial problem, we can ignore the upgrade recipe and just run on labs:

```sql
UPDATE tag SET value="", recjson_value="_collections" WHERE name="collection";
```

This is what I did the first time and worked.

**Comment by jalavik** [comment]
Thanks for the info @jmartinm. This worked on production. Closing issue.
