### ISSUE TITLE
RT ticket for (arXiv) record selected as CORE

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#2584]
## Expected Behavior

I'm afraid we need RT tickets for HEP-curation(?) for arXiv records selected as CORE. There is no other book-keeping as far as I know. RT tickets for other submissions will be needed too, though we (@annetteholtkamp ) can live without for a while.

Is that planned, should it already happen?

## Current Behavior

I don't see an RT ticket for this record in BibEdit
https://labs.inspirehep.net/holdingpen/690622
http://inspirehep.net/record/1613938

**Comment by annetteholtkamp** [comment]
For user submissions an rt ticket is already created for core papers. So it should be easy to do this for arXiv records as well.

- Annette


On Aug 2, 2017, at 9:45 AM, ksachs <notifications@github.com<mailto:notifications@github.com>> wrote:

Expected Behavior

I'm afraid we need RT tickets for HEP-curation(?) for arXiv records selected as CORE. There is no other book-keeping as far as I know. RT tickets for other submissions will be needed too, though we (@annetteholtkamp<https://github.com/annetteholtkamp> ) can live without for a while.

Is that planned, should it already happen?

Current Behavior

I don't see an RT ticket for this record in BibEdit
https://labs.inspirehep.net/holdingpen/690622
http://inspirehep.net/record/1613938

**Comment by michamos** [comment]
It looks simple indeed:
take https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/workflows/article.py#L259-L271 out of the `IF(is_submission,...)` (and rename `NOTIFY_ACCEPTED` that does not fit).

**Comment by jacquerie** [comment]
For clarity: this was closed because the code that fixes this has been merged in `master`, but it will be available on Labs when we fix a problem that's preventing us from deploying. Sadly we don't have an ETA for that.
