### ISSUE TITLE
Show keywords

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2701]
In the document's detailed page, no need to have a popup to display keywords, but it should display them directly on the page (instead of 'Show 16 keywords')

![key](https://user-images.githubusercontent.com/24955201/29923587-5bab5a86-8e5a-11e7-8e37-ffea50acabb5.PNG)

**Comment by jmartinm** [comment]
@StellaCh We were checking with @Dinika and the previous code that was working was showing the first 10 keywords and then the link to Show all X keywords. Since there might be many keywords it might be better to keep that behaviour instead of just showing all of them.

By the way, in the metadata there is a keyword called `* Automatic Keywords *`, do we want to filter it out in the display or show it? Or shall we instead remove it when importing the records and create a new field that captures the meaning of that? @ksachs @fschwenn

**Comment by fschwenn** [comment]
The `* Automatic Keywords *` was a work around.
I thought we would have a `curated_relation` for the keywords in the new schema. In that case  `* Automatic Keywords *` would not end up in the keywords but instead the "real" INSPIRE keywords for a record with `* Automatic Keywords *` would get a `curated_relation=False` and those without a `curated_relation=True`. The display should indicate whether the keywords are curated or not.

However the usual cataloguer will never curate INSPIRE keywords. For them the INSPIRE keywords could be even completely hidden withe a `Show INSPIRE keywords` button just in case.

The INSPIRE keywords are curated by external experts (see #2654)

**Comment by StellaCh** [comment]
@jmartinm Yes, showing a few in the beginning is fine, the previous code is ok then.

**Comment by jmartinm** [comment]
Ok, thanks @fschwenn 

So if I understand correctly by looking at the schema (https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/hep.yml#L912-L991) then the keywords that have `schema: INSPIRE` correspond to `* Automatic Keywords *` and the ones in free form from authors will not have any content in `schema`. @michamos maybe you can clarify that this is correct.

If that is the case, shall we display a bit more info in the keywords box? Like:
Author Keywords: foo bar
Automatic Keywords: baz

@StellaCh that can be something to check with a few users.
