### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2703]
When comparing the detailed view of the same record on legacy and labs, we see some links missing
Eg: links to OSTI and ADS are missing from Labs:  https://labs.inspirehep.net/literature/212819 

![osti2](https://user-images.githubusercontent.com/24955201/29924504-73596a08-8e5d-11e7-9dc9-e3e4a9f942c7.PNG)

Whereas we see them in Legacy: https://inspirehep.net/record/212819
![osti](https://user-images.githubusercontent.com/24955201/29924503-709fc032-8e5d-11e7-85a5-d34b3c6bf474.PNG)

**Comment by michamos** [comment]
The reason for this is that there are really 3 type of links here:
- external links in `8564` which are migrated to `urls. Those are present.
- internal links in `8564`. Those represent attached documents (should populate `documents` field) and are currently not handled correctly.
- links to records on other platforms, computed from `035`/`external_system_identifiers`. They are not present either.

**Comment by jmartinm** [comment]
So for the moment, the only action we can take is to show the external links. 

The template is https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_HTML_detailed_macros.tpl#L182-L237 so that part needs to be reviewed to make sure it works correctly.

**Comment by StellaCh** [comment]
Is this done @Dinika ? if yes, please feel free to close it

**Comment by michamos** [comment]
are the internal links displayed too?
