### ISSUE TITLE
literaturesuggest: be less strict in DOI input

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2712]
## Expected Behavior
the DOI input box should be less strict and attempt to normalize the DOI.
It should:

- strip whitespace
- strip leading `doi:`
- strip leading `(https?://)?(dx\.)?doi.org/`

## Current Behavior
A DOI needs to be entered without any prefix, that is starting with `10.`.

## Steps to Reproduce (for bugs)

1. Enter a DOI starting with `doi:`
2. Watch the exception on sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/865011/

**Comment by jmartinm** [comment]
So there are a 2 different things being asked to do here:

1. Relax the validator on the doi input ([here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/forms/validation_utils.py#L39)) in order to allow for `(https?://)?(dx\.)?doi.org/`.

2. Add a new normalizer ([here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/literaturesuggest/views.py#L90)) that will clean up the DOI value to make it conform with the [schema](https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/hep.yml#L698)

**Comment by iulianav** [comment]
@michamos I believe step 2 is wrong because the import happens before the submit and a get request is performed here https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/crossref/views.py#L41
