### ISSUE TITLE
search: endpoint that returns only `recid`s of matching records

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspire-next#2840]
Currently `search` api returns elasticsearch records that matches with the query, but for https://github.com/inspirehep/record-editor/issues/226, receiving complete records is gonna be too much unnecessary network usage, because we need `db` records and optionally fetch them as they navigate.

Thus it would be good to have an option to make `search` returns only `recid`s.  Maybe a new serializer?

**Comment by jmartinm** [comment]
One option is to add a new serializer to https://github.com/inspirehep/inspire-next/blob/master/inspirehep/config.py#L342 . Then that serializer could strip out all fields and return to the client only control_numbers. Issue with this is that the query to ES on the backend will still request all the fields which is unnecessary, since all the serializers share the same [search_factory](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/search/search_factory.py#L38) which does not filter any fields.

Second option is to have a view on the editor API that calls ES using our parser and asks only for control_number, like [this example](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/theme/views.py#L352-L357)

**Comment by harunurhan** [comment]
Second options seems like a better practice to me, but as long as I got the recids only I don't mind how you want it to be implemented on backend 😄

**Comment by harunurhan** [comment]
so @jmartinm any preferred way to do this? I think @chris-asl wants to take it over?

**Comment by jmartinm** [comment]
> so @jmartinm any preferred way to do this? I think @chris-asl wants to take it over?

We can do the view on the editor. Seems like a good option to me.

**Comment by chris-asl** [comment]
As discussed with @jmartinm IRL, I will add this endpoint in `editor/views` with this permission `@editor_use_api_permission.require(http_exception=403)`, as well.

**Comment by chris-asl** [comment]
After having implemented I need some feedback:
1. Since we're _searching_ and getting `recids`, wouldn't it make more sense to have this endpoint in the `search/api` module? 
Also, the endpoint could be `/api/literature/recids`. What do you think? @jmartinm 
2. @harunurhan any requirement regarding the size of the results? ([related](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html))
