### ISSUE TITLE
Create an exception module for Inspire

### ISSUE THREAD

**Issue by zzacharo** [inspirehep/inspire-next#2896]
Create a module with a common class for Inspire exceptions that wraps every underlying exception and use this one all over code base.

**Comment by StellaCh** [comment]
Is there any progress on that @zzacharo ?

**Comment by zzacharo** [comment]
@StellaCh nope it was more like a future good to have feature. But I didn't started it eventually.

**Comment by jacquerie** [comment]
We probably don't want to do this: while this is good practice when writing a library (so that users of your library will only need to catch one exception type), this doesn't make too much sense in an application, since a 500 code is an exceptional state, not something that you expect your users can trigger deterministically.

The only exception (sigh...) is in the workflows, where raising an exception stops the workflow in error state, which is useful to signal that something requires developer attention. But in fact we already have a module for workflow errors: https://github.com/inspirehep/inspire-next/blob/d8ff58fc09c31899d5aa76cc9b9b474d17a3022f/inspirehep/modules/workflows/errors.py.
