### ISSUE TITLE
Tuning of elasticsearch

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#296]
Elasticsearch configuration should reflect the INSPIRE data model, whatever that means. We should ensure this is compatible with the invenio-query-parser.

**Comment by jmartinm** [comment]
Also, we should port the `indexes` we used to have in production, like 
![screen shot 2015-09-04 at 1 41 11 pm](https://cloud.githubusercontent.com/assets/580727/9682843/b6d7bd56-530a-11e5-9bf0-d975d8c926fc.png)

So that they aggregate the right fields to make them searchable. We can use [ES ``copy_to``](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html#copy-to) for that.

**Comment by jmartinm** [comment]
Regarding this, for the Invenio-equivalent keywords supported by the Spires syntax https://github.com/inspirehep/invenio-query-parser/blob/master/invenio_query_parser/contrib/spires/config.py#L26

they should be added to the inspire/config https://github.com/inspirehep/inspire-next/blob/master/inspirehep/config.py#L292 mapping to the correct field in our data model.

**Comment by jalavik** [comment]
Work started in #641

**Comment by jmartinm** [comment]
Closing this as #682 #683 and #685 have the concrete tasks.
