### ISSUE TITLE
Formatting of records

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#297]
Records should have a nice brief and detailed representation, compatible with the new INSPIRE data model.

**Comment by jmartinm** [comment]
Brief records
=========

* [ ] HEP @nikpap 
* [ ] Authors
* [ ] Institutions
* [ ] Conferences
* [ ] Jobs
* [ ] Experiments
* [ ] Journals


Detailed records
=========

* [ ] HEP @nikpap 
* [ ] Authors
* [ ] Institutions
* [ ] Conferences
* [ ] Jobs
* [ ] Experiments
* [ ] Journals

**Comment by jmartinm** [comment]
Until we reach the following milestone https://github.com/inspirehep/inspire-next/milestones/Enabling%20authors I assume there is no need for the formatting of profiles and author search results locally in INSPIRE Labs?

Instead all author names in HEP papers will have a link like `https://inspirehep.net/author/profile/Suman%2C%20V.?recid=1390187&ln=en` that will resolve in production to the correct profile.

Note that `prodsync` has to keep the record ids so that profiles resolve properly.

**Comment by kaplun** [comment]
What's `prodsync`?

**Comment by kaplun** [comment]
> I assume there is no need for the formatting of profiles and author search results locally in INSPIRE Labs?

:+1:

**Comment by kaplun** [comment]
@jmartinm I have added Data and Software to the list of formats, because they definitively require love:
https://inspirehep.net/record/1391413
https://inspirehep.net/record/1390902

**Comment by jmartinm** [comment]
> @jmartinm I have added Data and Software to the list of formats, because they definitively require love:
https://inspirehep.net/record/1391413
https://inspirehep.net/record/1390902

We have software :open_mouth: !

For the data one, probably we are able to reuse some parts from the HepData one.

**Comment by jmartinm** [comment]
This is too broad issue, and parts of it have been tackled. I will close it and we can reopen individual ones.
