### ISSUE TITLE
INSPIRE beard client

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#301]
Toghether with the beard server (#300) we shall develop the client part that would:
* [x] collect all modified records WRT their signatures (if Invenio allows that), and the claims/unclaims that have happened since last time.
* [x] retrieve all the affected blocks (given a signature in a paper it will belong to a very defined and stable block, e.g. based on a transformation of a surname, see: https://github.com/inveniosoftware/beard/blob/master/beard/clustering/blocking_funcs.py#L174) 
* [x] send to beard all the records and all the signatures and all the claims and all the cluster linked with the affected blocks for beard to give back the new cluster
* [x] rematch the new clusters against the known ones (a.k.a. profiles), and in case create/delete some of them. This must be done respecting explicitly claims and unclaims.
* [x] port to Invenio 3 (@jlavik)

**Comment by kaplun** [comment]
@MSusik, @glouppe please feel free to amend this task as you deem appropriate

**Comment by glouppe** [comment]
Just a comment regarding the design this is taking. Beard has been developed as a _library_ providing all the tools needed to implement author disambiguation. In particular, the `examples` folder is only meant to  illustrate how put all these pieces together to solve disambiguation.  They are not meant to be used as an application themselves. 

In other words, I would rather see a single `inspire-disambiguation` module implementing tasks for author disambiguation (this can be copy pasted from the examples in beard), tasks for matching current and predicted clusters, tasks for getting signatures from records, etc rather than a collection of many decoupled modules (`invenio-beard`, `beard-server`, the glue for putting that into the overlay, etc). 

Or I would even first start by having the machinery working in the inspire overlay only, and only then think about generalizing it to other invenio instances.

Just my 2 cents.

**Comment by kaplun** [comment]
Sure `invenio-beard` could be part of the Overlay, but what would be the benefit?
The fact that we package all these tasks in the form of an Invenio module doesn't imply that is generic. On the other hand it will allow us to lower the barrier for making it generic in the future. 

Beside `beard-server` should really leave as a separate module, since it is a wrapper of beard library that would live on separate machine. It wouldn't make sense to have `beard-server` in INSPIRE overlay.

IMHO, the current decoupling represent on which piece of hardware each task is going to be executed.

**Comment by kaplun** [comment]
> (invenio-beard, beard-server, beardy_json, the glue for putting that into the overlay, etc).

Note `beardy_json` should become `invenio-beard`. Note also that we no longer need to factor out utils from `beard` as anyway @jalavik  is looking into installing the whole numpy machinery via docker, as HepData is doing, so Travis won't be a problem.

**Comment by jalavik** [comment]
I can get behind the idea that `invenio-disambiguation` is perhaps a better name than `invenio-beard` as to not couple package name with implementation but rather the goal. In that same breath, we could say that `invenio-grobid` should be called `invenio-pdfextractor` as well.

I am fine with keeping the beard library, beard-server and Invenio glue separate, although I know little of what is behind these terms.

**Comment by jacenkow** [comment]
Check #1353
