### ISSUE TITLE
python setup.py test is testing too much

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#359]
Currently `python setup.py test` is looking for tests *everywhere*, thus trying to execute every single file. Instead it should look only into inspire/testsuite.

BTW shall we move the testsuite under the more standard /tests folder?

**Comment by jalavik** [comment]
There is a PEP8 check as part of the pytest config that is checking every file, so that should be fine. It's true that if tests are found elsewhere in the code (e.g. like the ones under author), then it executes them. Overall I am not sure it's gonna be a problem. I guess we could move them under /tests as proposed anyway.

**Comment by kaplun** [comment]
Ah I see. Then it does make perfect sense. Thanks for the explanation. (I'll close the ticket, as it's not really necessary the move to /tests)
