### ISSUE TITLE
Fix formats according to data model changes

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#403]
After https://github.com/inspirehep/inspire-next/pull/400 gets merged all formats `bibtex`, `CV` and friends need to be amended to fit the new model.

**Comment by jalavik** [comment]
While updating the schema, I have tried to change all usages everywhere (including bibtex, latex formats, submissions, workflows etc.). However, I might have missed some parts, so this should still be verified.

**Comment by jalavik** [comment]
So @ioannistsanaktsidis is updating these formats now for BibTeX output and something came up when running it over the demo records.

Since across our collection we may have a different data model, e.g. HEP vs Experiments, we would have to amend the BibTeX/LateX formats to export differently per collection. E.g. titles.title vs. title. 

Does it make sense to even offer BibTeX/LaTeX export for non-HEP collections? Authors perhaps, but others? @kaplun @annetteholtkamp @jmartinm

**Comment by kaplun** [comment]
Actually Authors nope. IMHO only records in HEP (i.e. of document type) should have a BibTeX/LaTeX export. In the future also records in the Data collection might have such export, though.

**Comment by jmartinm** [comment]
Fixed https://github.com/inspirehep/inspire-next/pull/445
