### ISSUE TITLE
Enable Selenium Grid - Travis integration

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#433]
Would be great to integrate Github and Selenium Grid. After Travis runs, [Selenium](https://github.com/SeleniumHQ/selenium/wiki/Grid2) would run.

There is a docker image available for Selenium (https://github.com/SeleniumHQ/docker-selenium) so we could host it ourselves ( like the converter for HepData @eamonnmag ).

Then we would need a hook on Github to call our Selenium Grid.

**Comment by jmartinm** [comment]
@eamonnmag we can create a common Selenium Grid service and use it for INSPIRE, HepData and so on.

**Comment by eamonnmag** [comment]
@jstypka started on Selenium grid for HEPdata but had a lot of troubles. Jan, could you give an update to Javier about it?

**Comment by jstypka** [comment]
We've used [SauceLabs](https://saucelabs.com/) for this. It looked pretty cool at the beginning, but I had big problems with getting it to work and Selenium package itself.

For example tests failed for weird reasons like not finding a button on a page which has not loaded yet. The other issue was that on some configurations, they support only certain screen resolutions which were quite low (`1024x768` if I remember correctly), so it was difficult to test e.g. facets on this configurations. It's also awkward when you have a lot of JS happening and things loading and showing dynamically - Selenium didn't seem to be made for that.

But maybe it will work better for you. I can help with setting up SauceLabs because it was quite time-consuming at the beginning and I think I still have the code for that.

**Comment by jmartinm** [comment]
Were you using a free version of SauceLabs or paying for it? If there is a free version, is it enough?

**Comment by jstypka** [comment]
It's free for [OpenSource](https://saucelabs.com/opensauce/) projects and it's totally enough

**Comment by jmartinm** [comment]
Ah very nice! So if you can dig the code you used for the integration let me know and we do another try to see if we can make it work.

**Comment by kaplun** [comment]
:+1: In the past we used selenium (with Invenio legacy) and bumped into similar troubles you mention, but sensible workarounds had been found.

https://github.com/inveniosoftware/invenio/commit/6ff405046369ba34a3e3fa24caf46b92de10a051

**Comment by jmartinm** [comment]
Selenium is now integrated.
