### ISSUE TITLE
add correct material type to plots

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#463]
Currently all urls go to the same place in the schema. So a file with plots and and arXiv PDF looks like:

```
 "urls.url": [
                  "http://inspirehep.net/record/1090018/files/figures_2LoopDiags.png",
                  "http://inspirehep.net/record/1090018/files/figures_3LoopDiags1of4.png",
                  "http://inspirehep.net/record/1090018/files/figures_3LoopDiags2of4.png",
                  "http://inspirehep.net/record/1090018/files/figures_3LoopDiags3of4.png",
                  "http://inspirehep.net/record/1090018/files/figures_3LoopDiags4of4.png",
                  "http://inspirehep.net/record/1090018/files/figures_CoupPlot2s2f.png",
                  "http://inspirehep.net/record/1090018/files/arXiv:1202.4757.pdf"
               ],
               "urls.description": [
                  "00000 Diagrams that contribute to $q$ at two-loop order.",
                  "00001 (3)",
                  "00002 (3)",
                  "00003 (3)",
                  "00004 Diagrams that contribute to $q$ at three-loop order.",
                  "00005 RG evolution of the couplings in the model with two real scalars and two Weyl fermions on a scale-invariant limit cycle as a function of RG time. Here $\\epsilon=0.01$."
               ]
```

It would be nice if there was a way to filter the urls that are plots in order to show them in detailed view without everytime having to do some guessing based on `filename` and `png`.

Do you think we should amend the `dojson` import to add an appropriate `material_type` for all plots? (based on this guessing)

And in the `plotextractor` we would also add the `material_type`

**Comment by jalavik** [comment]
The big missing piece is that we cannot yet attach any files to records on labs. On prod we showed plots as they were attached with bibdocfile. These URLs from the demo records are then only treated as external links so my question is: (1) shall we display them from inspirehep.net even if they are not "attached" (or have a local copy)? or, (2) shall we implement a simple document attacher or `invenio-documents`, then show attached plots etc.?

That said, I guess for some links we need to figure out which is the PDF, or landing page etc. and indicate it somehow, so I think we would need to use the `material_type` as you suggest.

arXiv records are special since we need to link to the PDF on arXiv instead of locally.

Potentially we can also enrich these 8456 fields from production with extra info from bibdocfile. @kaplun 

In regards to the `plotextractor`, it outputs a list of dicts with info for each plot so the material type would need to be an invenio/inspire thing added in our workflow tasks.

**Comment by jmartinm** [comment]
>These URLs from the demo records are then only treated as external links so my question is: (1) shall we display them from inspirehep.net even if they are not "attached" (or have a local copy)? or, (2) shall we implement a simple document attacher or invenio-documents, then show attached plots etc.?

As step 1 for end-of-november launch I would display them from inspirehep.net. Hopefully Invenio comes with `invenio-documents` soonish

**Comment by jalavik** [comment]
Right. So perhaps a combination of enriching bibdocfile attached 8564 URLs with bibdocfile info for the enriched MARCXML export, with some simple filename based detection during dojson conversion?

**Comment by kaplun** [comment]
Yes, @egabancho is working actively on that.

**Comment by kaplun** [comment]
BTW I also vote for postponing handling documents. Since any way Prod is still master for everything we can simply put links to it and not worry about documents, yet.

**Comment by kaplun** [comment]
> Potentially we can also enrich these 8456 fields from production with extra info from bibdocfile. @kaplun

Yes, I can enhance my MARCXML enhancer and add info directly sitting in the bibdocfile table. Albeit this will mean re-restarting the dump :-)

**Comment by jacquerie** [comment]
`documents` and `figures` are already split in the schema since https://github.com/inspirehep/inspire-schemas/commit/b18cee8845c0ed4ab44d3d9e5eb36e5d545cadde, so the original issue can be closed. How to treat the files etc. is what currently @zzacharo is doing, and we already have lots of issues about that.
