### ISSUE TITLE
Known experiments list

### ISSUE THREAD

**Issue by Panos512** [inspirehep/inspire-next#556]
We are going to need a list of the known experiments in order to check and correct misspelled experiment names inside records. This will be used to avoid showing duplicate experiments in the facets (e.g. LHC-LHB and LHC-LHb at the same time).

**Comment by annetteholtkamp** [comment]
You find all Inspire exp names in the experiments collection in the field 119__a.

- Annette

On Nov 25, 2015, at 11:30 AM, Panos Paparrigopoulos <notifications@github.com<mailto:notifications@github.com>> wrote:


We are going to need a list of the known experiments in order to check and correct misspelled experiment names inside records. This will be used to avoid showing duplicate experiments in the facets (e.g. LHC-LHB and LHC-LHb at the same time).

**Comment by Panos512** [comment]
That would be very helpful! But are we sure that all those experiments are valid? i.e. in the demo records that we are now using for labs the record with id: 559118 has 'CERN-LHC-LHCB' (instead of CERN-LHC-LHCb) as the experiment name.

**Comment by annetteholtkamp** [comment]
119__a is our standard. Of course, as always, some metadata are unclean.

- Annette

On Nov 25, 2015, at 11:48 AM, Panos Paparrigopoulos <notifications@github.com<mailto:notifications@github.com>> wrote:


That would be very helpful! But are we sure that all those experiments are valid? i.e. in the demo records that we are now using for labs the record with id: 559118 has 'CERN-LHC-LHCB' (instead of CERN-LHC-LHCb) as the experiment name.

**Comment by jacquerie** [comment]
I'd say that this XML: https://inspirehep.net/search?ln=en&cc=Experiments&ln=en&cc=Experiments&p=&action_search=Search&sf=experimentname&so=a&rm=&rg=2813&sc=0&of=xm&ot=119 contains the answer to your question.

BTW, what's the meaning of the `119__u` subfield? I see that sometimes it's used to denote the University/Institution, sometimes for additional notes. (More in general, where can I find this information? In this case it's not [here](https://twiki.cern.ch/twiki/bin/view/Inspire/DevelopmentRecordMarkup)).

**Comment by annetteholtkamp** [comment]
You’ll have to go to https://twiki.cern.ch/twiki/bin/view/Inspire/DevelopmentRecordMarkupExperiments

In general, 119__u contains the lab. But many experiments don’t take place in a specific lab. 
Some of them are grouped under Astro.
Clearly, we should do better in the new data model. Since we now have subjects w could maybe just eliminate the Astro tag in 119__u.

- Annette

**Comment by jalavik** [comment]
So, we can avoid **some** duplication by simply having a generic deduplication filter for *all* facets. E.g. `LHC-LHB` and `LHC-LHb` would be deduplicated if we convert to lowercase and then filter and picking one of them to display properly (not lowercase version). Indeed this will not catch `CERN-LHC-LHCb` though, but as @annetteholtkamp says it is due to bad metadata which we simply then have to clean.

**Comment by annetteholtkamp** [comment]
Actually CERN-LHC-LHCb is the right one

- A

**Comment by Panos512** [comment]
@jalavik Yeah that is what I am trying to do [here](https://github.com/inspirehep/inspire-next/pull/554). 

I am gonna extract a list from the xml Jacopo posted and use it as reference.
