### ISSUE TITLE
Fixes for Firefox

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#578]
There are some problems rendering the pages in Firefox.

* [x] Search bar is shortened

![screen shot 2015-11-30 at 11 29 11 am](https://cloud.githubusercontent.com/assets/580727/11469295/96f2567e-9755-11e5-8ad1-310a4a156721.png)

* [ ] Dropdowns do not display nicely.

![screen shot 2015-11-30 at 11 29 33 am](https://cloud.githubusercontent.com/assets/580727/11469306/a732f002-9755-11e5-8af9-795839730593.png)

One solution is to move to to `select2` https://select2.github.io/ and https://github.com/select2/select2-bootstrap-theme which we already have in our Bundles so that all dropdowns are consistent.

* [ ] Fonts look quite different on Firefox compared to Chrome. We need to see if is because of the `Lato` font or all of them look different.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm from a search I did the select tag is a known problem between firefox and chrome. The problem is the class='form-control' from bootstrap. For some reason firefox is not compatible with this. if you remove the class the select looks like this in both browsers: 
<img width="205" alt="screen shot 2015-12-04 at 11 55 28" src="https://cloud.githubusercontent.com/assets/7301890/11588028/ef60a1fa-9a7d-11e5-8df2-e95789407166.png">

I guess we can use the default select without the class and style it accordingly manually. What do you think?

**Comment by jmartinm** [comment]
I would still give a try to `select2`. It would make them look exactly the same in Firefox and Chrome and with a better style and some extra options.

**Comment by kaplun** [comment]
To be reopened if needed with Angular
