### ISSUE TITLE
Popup of Welcome to INSPIRE Labs can be annoying

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#584]
The popup currently is shown once per session and once closed it does not show until a new window is opened. This can be still too much so might be better to keep a cookie on the user's computer so that we don't show the popup again (with a timeout of say 1 week).

![screen shot 2015-11-30 at 1 51 44 pm](https://cloud.githubusercontent.com/assets/580727/11471975/7c3b7be4-9769-11e5-8d31-33717b83b618.png)

**Comment by salmele** [comment]
+1 for a more rare pop-up and the cookie, maybe even with a longer timeout.

**Comment by jalavik** [comment]
I've noticed also that the whole box is clickable so that when you click anywhere inside it - the box is closed. However you need to be a bit precise to hit the `click here` part to get to INSPIRE. I am wondering if it is better to force people to click the `x` to close it or if no-one else has experienced any issues with that it might just be me.
