### ISSUE TITLE
ElasticSearch nested authors creates too many documents

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#590]
Since the new mapping for authors with type `nested` was introduced, the number of documents in the ElasticSearch cluster grows as each of author creates a new document.

This was introduced to have a convenient way for `Beard` library to fetch only one author but might create performance issues.

We should either remove this functionality (and let `Beard` do the computation Python-side) or make sure it does not impact the cluster.

**Comment by kaplun** [comment]
I am checking and the situation is not so terrible. The truth is there are not so many documents having many authors. We tend to focus on them because of our CERN bias, but in fact they are a minority. So with this improvement it's true that there are more documents, but no so many. I tend to think they might be around 5x times more than just HEP records.

More precise numbers coming soon.

**Comment by kaplun** [comment]
OK. The exact number as of today is going to be 11091896 i.e. ~11M documents. I think it's feasible.

**Comment by kaplun** [comment]
Note: here are the detailed number: https://docs.google.com/spreadsheets/d/15TkP-bDemBmYL5SSgh-tlFGYBejEYZfk-roLmqyW4Go/edit?usp=sharing
